-- Reference schema for PostgreSQL/Supabase.
CREATE TABLE IF NOT EXISTS leads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    company VARCHAR(160) NOT NULL,
    email VARCHAR(255) NOT NULL,
    event VARCHAR(160) NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    follow_up_status VARCHAR(40) NOT NULL DEFAULT 'New',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leads_name ON leads(name);
CREATE INDEX IF NOT EXISTS idx_leads_company ON leads(company);
CREATE INDEX IF NOT EXISTS idx_leads_event ON leads(event);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(follow_up_status);
